package io.github.dk900912.oplog.service;

import io.github.dk900912.oplog.model.LogRecord;

/**
 * @author dukui
 */
public interface LogRecordPersistenceService {

    /**
     * @param logRecord a operation log generated by oplog component
     */
    void doLogRecordPersistence(LogRecord logRecord);

}
